Repository mytnguyen26/algo-shadow, pull requests merged in 2023-12, with the labels that each got.

#27 docs-spanning-up-authentication-service
  README.md
  packages/client/package-lock.json
Labels: documentation

#30 Refactoring Checkpoint
  package-lock.json
  packages/client/__tests__/algorithm.test.js
  packages/client/__tests__/dijkstra.test.js
  packages/client/coverage/base.css
  packages/client/coverage/block-navigation.js
  packages/client/coverage/coverage-final.json
  packages/client/coverage/dijkstrasolver.js.html
  packages/client/coverage/favicon.png
  packages/client/coverage/index.html
  packages/client/coverage/prettify.css
  packages/client/coverage/prettify.js
  packages/client/coverage/sort-arrow-sprite.png
  packages/client/coverage/sorter.js
  packages/client/index.html
  packages/client/package-lock.json
  packages/client/package.json
  packages/client/src/App.jsx
  packages/client/src/algorithm-solver/bstsolver.js
  packages/client/src/algorithm-solver/dijkstrasolver.js
  packages/client/src/algorithm-solver/heapsolver.js
  packages/client/src/components/AlgorithmSolver/BSTConcreteStrategy.js
  packages/client/src/components/AlgorithmSolver/DijkstraConcreteStrategy.js
  packages/client/src/components/AnalyzeGraph/BarChart.jsx
  packages/client/src/components/AnalyzeGraph/getBarChartData.js
  packages/client/src/components/GraphRenderer.js
  packages/client/src/components/GraphRenderer/animate.jsx
  packages/client/src/images/index.js
  packages/client/src/pages/Algorithm/AlgComponent/algorithmSpace.jsx
  packages/client/src/pages/Algorithm/AlgComponent/runtimeAnalysis.jsx
  packages/client/src/pages/Algorithm/AlgComponent/saveInputToLocalStorage.jsx
  packages/client/src/pages/Algorithm/Common/animationdata.js
  packages/client/src/pages/Algorithm/Common/common
  packages/client/src/pages/Algorithm/Common/common.js
  packages/client/src/pages/Algorithm/Common/digraphrenderer.js
  packages/client/src/pages/Algorithm/Common/treerenderer.js
  packages/client/src/pages/Algorithm/DijkstraComponent/Dijkstra.jsx
  packages/client/src/pages/Algorithm/DijkstraComponent/DijkstraGraph.jsx
  packages/client/src/pages/Algorithm/HeapComponent/animate.jsx
  packages/client/src/pages/Algorithm/HeapComponent/heap.jsx
  packages/client/src/pages/Algorithm/HeapComponent/heapmethod.js
  packages/client/src/pages/Algorithm/HeapComponent/heapmethod.jsx
  packages/client/src/pages/Algorithm/bst.jsx
  packages/client/src/pages/Algorithm/bstComponent/bstanimate.jsx
  packages/client/src/pages/Algorithm/bstComponent/bstmethod.js
  packages/client/src/pages/Algorithm/dijkstra.jsx
  packages/client/src/pages/Algorithm/heap.jsx
  packages/client/src/pages/Algorithm/test.jsx
  packages/client/src/pages/Home/component/algoList.jsx
  packages/client/src/pages/Home/component/navbar.jsx
  packages/client/src/pages/Home/contact.jsx
Labels: refactor

#38 Hotfixes
  README.md
  documents/Software_Requirement_Specification.pdf
  documents/client-side modules.png
  documents/software_design_document.pdf
  packages/client/coverage/coverage-final.json
  packages/client/coverage/index.html
  packages/client/coverage/pages/Algorithm/BST.jsx.html
  packages/client/coverage/pages/Algorithm/Hash.jsx.html
  packages/client/coverage/pages/Algorithm/Heap.jsx.html
  packages/client/coverage/pages/Algorithm/algo-component/AlgorithmSpace.jsx.html
  packages/client/coverage/pages/Algorithm/algo-component/SaveInputToLocalStorage.jsx.html
  packages/client/coverage/pages/Algorithm/algo-component/TableCreater.jsx.html
  packages/client/coverage/pages/Algorithm/algo-component/index.html
  packages/client/coverage/pages/Algorithm/algo-component/useTableData.jsx.html
  packages/client/coverage/pages/Algorithm/analyze-graph/BarChart.jsx.html
  packages/client/coverage/pages/Algorithm/analyze-graph/index.html
  packages/client/coverage/pages/Algorithm/index.html
  packages/client/coverage/utils/algorithm-solver/analyzeRuntime.js.html
  packages/client/coverage/utils/algorithm-solver/bstSolver.js.html
  packages/client/coverage/utils/algorithm-solver/dijkstraSolver.js.html
  packages/client/coverage/utils/algorithm-solver/hashTableSolver.js.html
  packages/client/coverage/utils/algorithm-solver/heapSolver.js.html
  packages/client/coverage/utils/algorithm-solver/index.html
  packages/client/coverage/utils/algorithm-solver/runtimeAnalysis.js.html
  packages/client/coverage/utils/barchart-analyze/getBarchartData.js.html
  packages/client/coverage/utils/barchart-analyze/index.html
  packages/client/coverage/utils/renderer/animationData.js.html
  packages/client/coverage/utils/renderer/common.js.html
  packages/client/coverage/utils/renderer/index.html
  packages/client/coverage/utils/renderer/treeRenderer.js.html
  packages/client/src/pages/algorithm/Dijkstra.jsx
  packages/client/src/pages/algorithm/Heap.jsx
  packages/client/src/pages/algorithm/dijkstra-component/Dijkstra.jsx
  packages/client/src/pages/algorithm/dijkstra-component/DijkstraGraph.jsx
  packages/client/src/pages/algorithm/dijkstra-component/useLinks.jsx
  packages/client/src/pages/algorithm/dijkstra-component/useNodes.jsx
  packages/client/src/pages/home/component/AlgoList.jsx
  packages/client/src/utils/algorithm-solver/analyzeRuntime.js
  packages/client/src/utils/algorithm-solver/bstSolver.js
  packages/client/src/utils/algorithm-solver/dijkstraSolver.js
  packages/client/src/utils/algorithm-solver/hashTableSolver.js
  packages/client/src/utils/algorithm-solver/heapSolver.js
  packages/client/src/utils/algorithm-solver/runtimeAnalysis.js
  packages/client/src/utils/renderer/animationData.js
  packages/client/src/utils/renderer/common.js
  packages/client/src/utils/renderer/digraphRenderer.js
  packages/client/src/utils/renderer/treeRenderer.js
Labels: documentation

#42 Add Experiment table for Hash Page
  documents/software_manual_testing_doc.pdf
  package-lock.json
  packages/client/package-lock.json
  packages/client/src/assets/style/hash.table.style.css
  packages/client/src/pages/algorithm/Hash.jsx
  packages/client/src/pages/home/About.jsx
  packages/client/tests/HashV.test.jsx
  packages/client/tests/dijkstra.test.js
  packages/client/tests/dijkstra.test.jsx
Labels: enhancement

#43 Hotfix add email and uncomment authentication
  packages/client/src/App.jsx
  packages/client/src/pages/home/About.jsx
  packages/client/src/pages/home/Contact.jsx
Labels: bug

#44 Hot fix
  packages/client/src/App.jsx
  packages/client/src/pages/home/About.jsx
  packages/client/src/pages/home/Contact.jsx
Labels: release
